Agnes app
Technigo/project-react-native-app pull request #102
Opened 2020-11-15 13:46 UTC by aagneshansson

My reflections on how this week's project turned out:
Very challenging but also a lot of fun. 

Things I'd like to have clarified or explained in more detail:
More about the terminal, how to tackle issues, how expo works, more about the techniques.

2020-12-09 09:02 UTC, EmOlsz requested changes

2020-12-09 09:02 UTC, EmOlsz commented on components/Dressage.js
> +      <PickButton onPress={() => { getExercise(); Vibration.vibrate() }}>
If you need to pass more than one function to event handler, you should rather create separate function and call it inside event handler

2020-12-09 09:02 UTC, EmOlsz commented on components/HomeScreen.js
> +    font-weight: bold, italic;
`italic` is possible value for `font-style`, not `font-weight`

2021-02-17 08:43 UTC, aagneshansson commented on components/Dressage.js
> +      image: require('../assets/Serpentin.gif'),
Ok thanks 🙌 I have named all imgs uppercase when importing them ..

2021-02-17 16:34 UTC, EmOlsz approved these changes

2021-03-09 12:45 UTC, closed without merging