Todolist
Technigo/project-react-native-app pull request #122
Opened 2020-11-16 17:04 UTC by JHarde

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-12-09 11:01 UTC, EmOlsz requested changes

2020-12-09 11:01 UTC, EmOlsz commented on components/FormInput.js
> +          setText("");
If we need to pass more than one line of code to event handler, then it's clear indicator for us to create separate function

2020-12-09 11:01 UTC, EmOlsz commented on components/Weather.js
> +        console.log(data);
Let's remove all console.logs from project

2020-12-09 11:01 UTC, EmOlsz commented on components/Weather.js
> +  console.log(weatherInfo);
Over here as well

2020-12-13 20:52 UTC, JHarde commented
I have implemented most of the changes now! I think I need some more time to try to figure out how to solve the change in FormInput though!

2020-12-14 16:13 UTC, EmOlsz commented
Great, good to hear that Joel! I think you might forgot to push your changes though, I cannot see any new commits since my review was done ;)

2020-12-14 16:43 UTC, JHarde commented
Ah of course, haha, fixing it now! :)

On Mon, 14 Dec 2020, 17:13 Maksymilian Olszewski <notifications@github.com>
wrote:

> Great, good to hear that Joel! I think you might forgot to push your
> changes though, I cannot see any new commits since my review was done ;)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-react-native-app/pull/122#issuecomment-744544848>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQ67OWGCMLY4EOLK3SRAJTSUY2R3ANCNFSM4TXNX5UQ>
> .
>

2020-12-14 16:47 UTC, JHarde commented
Taken care of now! There are some other things I'm going to try to
implement in this app during the Christmas break as well!

Den mån 14 dec. 2020 kl 17:43 skrev Joel Harde <joel.harde@gmail.com>:

> Ah of course, haha, fixing it now! :)
>
> On Mon, 14 Dec 2020, 17:13 Maksymilian Olszewski <notifications@github.com>
> wrote:
>
>> Great, good to hear that Joel! I think you might forgot to push your
>> changes though, I cannot see any new commits since my review was done ;)
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Technigo/project-react-native-app/pull/122#issuecomment-744544848>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AOQ67OWGCMLY4EOLK3SRAJTSUY2R3ANCNFSM4TXNX5UQ>
>> .
>>
>

2020-12-14 16:55 UTC, EmOlsz commented
Ok, noted down! I will wait for the last set of changes, and then I will approve whole project

2021-01-11 16:16 UTC, JHarde commented
Think I've managed to fix all the changes now! :)

2021-01-11 17:43 UTC, EmOlsz commented
Exactly, great job :) Project approved!

2021-01-11 17:43 UTC, EmOlsz approved these changes

2021-03-09 12:43 UTC, closed without merging