Estefanía Project react Native app
Technigo/project-react-native-app pull request #148
Opened 2021-04-10 13:31 UTC by esteficodes

My reflections on how this week's project turned out:
React native is quite complex to be learnt and handled in in just one week. Despite this, I was able to create the app I originally wanted to.

Things I'd like to have clarified or explained in more detail:
I think React Native would deserve at least two weeks in the programme. I feel like I would like to learn how to do so much more!

2021-04-17 17:14 UTC, KarolCislowski requested changes
I tried to run your app but I got this error: `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

2021-04-17 17:14 UTC, KarolCislowski commented on screens/HomeScreen.js
> +      .catch(err => console.log(err));
remember to remove all console logs before requesting pull.

2021-04-19 14:37 UTC, esteficodes commented
> I tried to run your app but I got this error: `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

Hi, Karol! 
Could you be a little bit more specific as to what can I try here or what is exactly failing? I'm a little bit lost here.

2021-05-02 18:41 UTC, KarolCislowski approved these changes
Sweet, 😸  Now it works 🥳

2021-11-01 15:14 UTC, closed without merging