Drawer navigation
Technigo/project-react-native-app pull request #156
Opened 2021-04-11 11:34 UTC by Yennie-Leek

My reflections on how this week's project turned out:
This was a bit of a struggle. Started with technical issues and couldn't start working with the code until later in the week. When I finally got it up and running I was a bit drained and confused what to actually do and how to start. But it worked out with some help from one friend in my team. 
I still have technical issues and cant connect to expo in my mobile, which also means I cant deploy it there. 
Hopefully I can have a look at it later and make it work. 

Things I'd like to have clarified or explained in more detail:

2021-04-18 12:39 UTC, KarolCislowski requested changes
I couldn't run your app. 😭  These are error messages that I saw on my device: 
![image](https://user-images.githubusercontent.com/50926159/115145786-a53e8600-a053-11eb-946e-13351ec2fd98.png)

![image](https://user-images.githubusercontent.com/50926159/115145781-9a83f100-a053-11eb-879a-8a9670eaedaf.png)

2021-04-18 12:39 UTC, KarolCislowski commented on screens/ChuckNorris.js
> +    .catch(err => console.error(err))
Remember to remove all console outputs before requesting the pull.

2021-05-20 09:33 UTC, Yennie-Leek commented
Hey! I have now created a snack so you will be able to view it live. I hope this will work as I still have issues to make the Expo work.. 
Link to my snack:
[https://snack.expo.io/@yennie/week-13-react-native](url)

2021-06-07 10:19 UTC, Yennie-Leek commented
Hey!
I have now created a snack so you will be able to view it live. I hope this will work as I still have issues to make the Expo work..
Link to my snack:
***@***.***/week-13-react-native

Kind regards, Yennie

On 18 Apr 2021, at 14:39, Karol Cislowski ***@***.******@***.***>> wrote:



@KarolCislowski requested changes on this pull request.

I couldn't run your app. 😭 These are error messages that I saw on my device:
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F50926159%2F115145786-a53e8600-a053-11eb-946e-13351ec2fd98.png&data=04%7C01%7C%7Cdb9f0ff1b6c94fe316c908d9026704c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543463742836964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VZyuGh57vLksIlTEYU%2FWc8w0I4UrR4bnSvi5AqPH0jg%3D&reserved=0>

[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F50926159%2F115145781-9a83f100-a053-11eb-879a-8a9670eaedaf.png&data=04%7C01%7C%7Cdb9f0ff1b6c94fe316c908d9026704c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543463742836964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rzrJk%2FHS1KTsMgJ8Tr3RWRSJOlqFHsyuFxc9gUeT1EU%3D&reserved=0>

________________________________

In screens/ChuckNorris.js<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechnigo%2Fproject-react-native-app%2Fpull%2F156%23discussion_r615390808&data=04%7C01%7C%7Cdb9f0ff1b6c94fe316c908d9026704c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543463742846961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UfGEZxIGFz3TbIA%2BCz2viJ9GY4FnTMZnOoNizl8t8Ko%3D&reserved=0>:

> +  font-size: 20px;
+`
+
+export const ChuckNorris = ({navigation}) => {
+
+  const [chuckNorris, setChuckNorris] = useState ('')
+
+  useEffect (() => {
+    fetchChuckNorrisList()
+  }, [])
+
+  const fetchChuckNorrisList = () => {
+    fetch('https://api.chucknorris.io/jokes/random')
+    .then(res => res.json())
+    .then(value => setChuckNorris(value))
+    .catch(err => console.error(err))


Remember to remove all console outputs before requesting the pull.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechnigo%2Fproject-react-native-app%2Fpull%2F156%23pullrequestreview-638324614&data=04%7C01%7C%7Cdb9f0ff1b6c94fe316c908d9026704c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543463742846961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A6ZXMQzF6YGULkSknxiqzT5LdHTgG1LmOmtHEK72kGs%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASDKI7NJD6A3Z2HXZ3YHLZLTJLHIJANCNFSM42XSBYHQ&data=04%7C01%7C%7Cdb9f0ff1b6c94fe316c908d9026704c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543463742856952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A%2BDwANRxjlJsDHBZMBrPH%2FGIFJatBIz62gV4LybrRys%3D&reserved=0>.

2021-11-01 15:14 UTC, closed without merging