New Habits App - Nathalie Nordström
Technigo/project-react-native-app pull request #78
Opened 2020-11-12 15:05 UTC by nathalienordstrom

My reflections on how this week's project turned out:

I think it's cool to be able to create an app, the amount of new information meant that I could not go all the way with my idea. I'm really proud of what I've done, and I will leave it now when it's not broken and the next time push it farther.

https://snack.expo.io/@nathalie-nordstrom/unnamed-snack

2020-12-01 14:52 UTC, EmOlsz requested changes
Hey Nathalie! Let's fix issues pointed out in my comments, after that I'll be able to approve your project :)

2020-12-01 14:52 UTC, EmOlsz commented on App.js
> +import  Habits from './Habits'
Shouldn't `Habits` be also in `/components` folder?

2020-12-01 14:52 UTC, EmOlsz commented on App.js
> +        component={HomePage}
Some wrong indentations

2020-12-01 14:52 UTC, EmOlsz commented on Habits.js
> +    // { text: 'write in your diary', key: ' 3 ' },
Let's delete this commented code

2020-12-01 14:52 UTC, EmOlsz commented on components/HomePage.js
> +            </Header>
I don't think you need empty tag

2020-12-01 14:52 UTC, EmOlsz commented on components/ToDoItem.js
> +`
This is styled component without styles - we don't need it :)

2020-12-01 14:52 UTC, EmOlsz commented on components/ToDoItem.js
> +        }}
We don't have to break line here, this is completely enough :

```
<TouchableOpacity onPress={() =>  pressHandler(item.key)}>
```

2021-02-22 14:22 UTC, HIPPIEKICK commented on components/HomePage.js
> +        </HomeContainer>
Nice job with the changes Nathalie! There are still some places that have a weird indentation, such as here 👆. Also, remember to indent styled components, e.g:
```
const Main = styled.View`
  flex:1;
  margin-bottom: 70px;
`
```
Also, remove unnecessary empty lines, and make sure you are consistent regarding semicolons.

2021-03-01 15:31 UTC, HIPPIEKICK commented on components/HomePage.js
> +        </HomeContainer>
This still applies 👆

2021-03-01 16:16 UTC, HIPPIEKICK approved these changes

2021-03-01 16:16 UTC, HIPPIEKICK commented on App.js
>    )
Missing semicolon in all files after `return ()`

2021-03-01 16:16 UTC, HIPPIEKICK commented on components/Add.js
> +`
Missing semi colon after all styled components in all files

2021-03-09 12:49 UTC, closed without merging