Project react-native-app - Karolin Albinsson
Technigo/project-react-native-app pull request #82
Opened 2020-11-13 11:17 UTC by karolinalbinsson

My reflections on how this week's project turned out:

I tried to keep it really simple this week and aimed only for blue level. Mainly because I did not enjoy working with react native, maybe because of all the strange errors and difficulties  that I faced with installations.

 I am happy that this project is done and that I have got the opportunity to work with native, at least I have learned that I do not like working with it and want to stick with web 👍 

Things I'd like to have clarified or explained in more detail:
-

2020-12-01 16:04 UTC, HIPPIEKICK requested changes
Really nice that you tried out the shake event! ⭐ You've got some really cool functionality going on and the structure of your project is good. However, your indentation is off in some places so please take a look at that :)

2020-12-01 16:04 UTC, HIPPIEKICK commented on App.js
> +  }, []);
⭐

2020-12-09 11:29 UTC, karolinalbinsson commented
Hi Matilda! Thank you for the feedback. I have made the changes requested.

2020-12-17 08:58 UTC, HIPPIEKICK commented on App.js
> +font-weight: bold`;
This should also be indented ;)

2020-12-17 08:59 UTC, HIPPIEKICK commented on App.js
> +import { ShakeEvent} from './components/ShakeEvent';
Semi colons or not - be consistent

2020-12-17 09:01 UTC, HIPPIEKICK commented
> Hi Matilda! Thank you for the feedback. I have made the changes requested.

Some indentation issues still, but approving now! Have a look at semi colon usage as well (be consistent).

2020-12-17 09:01 UTC, HIPPIEKICK approved these changes

2021-03-09 12:45 UTC, closed without merging