What to do on a rainy day ☔️
Technigo/project-react-native-app pull request #88
Opened 2020-11-13 14:49 UTC by Snabbina

My reflections on how this week's project turned out:
The det up and all the dependencies was a project on its own, otherwise cool to make a working mobile app in just a few days!

Things I'd like to have clarified or explained in more detail:

2020-12-07 10:32 UTC, EmOlsz requested changes

2020-12-07 10:32 UTC, EmOlsz commented on App.js
> +import { ThingsToDo } from './components/ThingsToDo'
Let's not forget about one empty line between outer and local dependencies!

2020-12-07 10:32 UTC, EmOlsz commented on components/ThingsToDo.js
> +import { Text, View, Vibration, TouchableOpacity } from 'react-native';
I see that sometimes you use single quotes and sometimes double quotes - let's try to be consistent about it

2020-12-07 10:32 UTC, EmOlsz commented on components/ThingsToDo.js
> +  const ThingsToDoArray = [
Uppercase names are reserved for components only, not for arrays

2020-12-07 10:32 UTC, EmOlsz commented on components/ThingsToDo.js
> +    const [thingtodo, setThingToDo] = useState({});
Wrong indentation over here ;)

2020-12-07 10:32 UTC, EmOlsz commented on components/ThingsToDo.js
> +      <ThingsToDoContainer style={{ backgroundColor: thingtodo.color }}>
If we decide to use styled components, then let's stick to it and do not pass styles via `style` attribute.
You can pass `thingtodo` value as prop to your styled component and later on use it there to define styles

2020-12-07 10:32 UTC, EmOlsz commented on components/ThingsToDo.js
> +          Vibration.vibrate();
If we need to execute more than one line of code, then we should move our logic to separate function and call it on `onPress` :

```
const myCustomFunc = () => {
  getThingsToDo();
  Vibration.vibrate();
}

return (
  <PickButton onPress={myCustomFunc} />
)
```

2021-02-11 11:55 UTC, Snabbina commented
Hello, made the changes requested on this project, is it ok now? /S

2021-03-09 12:50 UTC, EmOlsz approved these changes

2021-03-09 12:50 UTC, closed without merging