Claire Caudwell Uplifting quotes mobile app
Technigo/project-react-native-app pull request #95
Opened 2020-11-14 12:12 UTC by ClaireCaudwell

**My reflections on how this week's project turned out:**
Bit of a tough week. In the beginning I had a specific idea in mind, but was struggling with if my idea will work/if I can implement it in react native. This was down to the fact that I didn't know react native. That being said I read the documentation, watched a few videos and got some advice from others on how it could work. In the end I managed to achieve my goal and learnt a bunch of react native things along the way.  If you want to read more on what I achieved etc you can read my [README](https://github.com/ClaireCaudwell/project-react-native-app) 😊

**Things I'd like to have clarified or explained in more detail:**
How one can create a reusable component that's a link between pages which you can insert into another component. Also how I can make my code less but still have the outcome I have now.

I managed to upload my github repo to a snack on expo.io [here](https://snack.expo.io/@clairecaudwell/github.com-clairecaudwell-project-react-native-app) 📱💻 If you do check it out please check out my [README](https://github.com/ClaireCaudwell/project-react-native-app) for the best way to view in on my snack ❤

2020-12-08 12:02 UTC, EmOlsz requested changes

2020-12-13 17:39 UTC, ClaireCaudwell commented on App.js
> +import Sun from './components/Sun';
Hi @EmOlsz 😊 Yes I know. Initially I did have it as one component where I was mapping over the array of each quote. But the problem I had was that I wanted to place each of my icons, sun, heart, hand etc in a specific place. So I had to create a component for each of them! Before I was getting a grid like layout, but I wanted to customise it. I think I wrote about this in my read me and maybe I can arrange a 1:1 to get a advice if there is any other way of placing the icons specifically without having to have multiple components that are almost identical.

2020-12-13 17:39 UTC, ClaireCaudwell commented on components/Bird.js
> +import BackgroundImage from './icons/Background.png';
Noted 👍

2020-12-13 17:40 UTC, ClaireCaudwell commented on components/Bird.js
> +      flex: 1,
Ok perfect and noted. Thanks for the feedback 👍

2020-12-13 17:41 UTC, ClaireCaudwell commented on components/QuoteList.js
> +                        <HeartButton onPress={()=> navigation.navigate('Heart')}>
@EmOlsz Yep I agree, but see my comment to your first comment about what I was trying to achieve 😊

2021-02-18 09:20 UTC, EmOlsz approved these changes

2021-03-09 12:45 UTC, closed without merging